STRIPES-708: Discourage placeholders in I18N documentation
folio-org/stripes pull request #105
Opened 2020-10-30 17:14 UTC by julianladisch

I've added these sections:
* Don't split sentences
* Use placeholders for dynamic content
* Avoid placeholders

I've removed the example section because it shows discouraged placeholders use.

https://issues.folio.org/browse/STRIPES-748 "Add example section to doc/i18n.md" exists. Since October 2020 I've requested that a Stripes developer fixes the example section but no one was able to do this task. This justifies to remove the example section until someone picks up [STRIPES-748](https://issues.folio.org/browse/STRIPES-748).

2021-05-25 11:38 UTC, zburke approved these changes
Thanks for this! 

It's really unfortunate that I chose `ControlledVocab` as an example in this documentation because the way it was written precludes correct i18n 😢 .

2021-05-25 12:23 UTC, MikeTaylor requested changes
Thanks for doing this. See minor comments.

2021-05-25 12:23 UTC, MikeTaylor commented on doc/i18n.md
> +In the above section, placeholders were used for identifiers. They can also safely be used for things like names, or titles, etc. However, avoid placeholders the placeholder is known at compile time
"avoid placeholders the placeholder" must be a typo, but it's not obvious what for.

2021-05-25 12:23 UTC, MikeTaylor commented on doc/i18n.md
> +## Avoid placeholders
This heading is a misleading summary of the section. I would recommend something like "Be cautious when using placeholders" or "avoid substituting nouns and verbs or placeholders".

2021-05-25 12:23 UTC, MikeTaylor commented on doc/i18n.md
> +If there are pre-defined and custom types handle them separately:
"If there are both pre-defined ..." would be clearer.

2021-05-25 12:54 UTC, julianladisch commented on doc/i18n.md
> +In the above section, placeholders were used for identifiers. They can also safely be used for things like names, or titles, etc. However, avoid placeholders the placeholder is known at compile time
Resolved.

2021-05-25 12:54 UTC, julianladisch commented on doc/i18n.md
> +## Avoid placeholders
Resolved.

2021-05-25 12:54 UTC, julianladisch commented on doc/i18n.md
> +If there are pre-defined and custom types handle them separately:
Changed as suggested.

2021-05-25 12:57 UTC, MikeTaylor commented on doc/i18n.md
> +## Avoid substituting nouns and verbs or placeholders
or -> for. Sorry :-)

2021-05-25 12:57 UTC, MikeTaylor commented on doc/i18n.md
> +In the above section, placeholders were used for identifiers. They can also safely be used for things like names, or titles, etc. However, avoid placeholders the placeholder is known at compile time
Confirmed.

2021-05-25 12:57 UTC, MikeTaylor commented on doc/i18n.md
> +## Avoid placeholders
You copied the typo in my suggested title :-)

2021-05-25 12:57 UTC, MikeTaylor commented on doc/i18n.md
> +If there are pre-defined and custom types handle them separately:
Confirmed.

2021-06-03 16:11 UTC, MikeTaylor approved these changes
Thanks!

2021-06-03 20:38 UTC, merged