Move Jest/RTL doc into main Stripes docs
folio-org/stripes pull request #164
Opened 2022-04-15 21:09 UTC by ryandberger

- Fulfills [STRIPES-768](https://issues.folio.org/browse/STRIPES-768)
- Trimmed down original document from https://github.com/folio-org/ui-plugin-eusage-reports/blob/master/doc/testing-with-jest-and-rtl.md
- Many thanks to @MikeTaylor for the original document

2022-04-19 11:10 UTC, MikeTaylor approved these changes
Nice to see this in a location where developers new to Jest/RTL are more likely to find it.

2022-04-19 19:09 UTC, zburke requested changes
I noticed a few minor typos that should be fixed and I think it may be better to use canonical URLs that reference specific commits rather than relative URLs that reference branches. 

The rest of my comments you can take or leave.

2022-04-19 19:09 UTC, zburke commented on doc/unit-testing-with-jest-and-rtl.md
> +	runTestOptions = '--coverage'
GitHub actions is the new standard way; Jenkins is the grandfathered way. Regardless, how about:
> For projects using Jenkins for CI, add these lines to `./Jenkinsfile` ...
> For projects using GitHub Actions for CI, add these lines to `./.github/workflows/build-npm.yml`:
```
env:
  YARN_TEST_OPTIONS: '--ci --coverage --colors'
  JEST_JUNIT_OUTPUT_DIR: 'artifacts/jest-junit'
  JEST_COVERAGE_REPORT_DIR: 'artifacts/coverage-jest/lcov-report/'
...
steps:
  - name: Run yarn test
    run: xvfb-run --server-args="-screen 0 1024x768x24" yarn test $YARN_TEST_OPTIONS JEST_COVERAGE_REPORT_DIR: 'artifacts/coverage-jest/lcov-report/'

  - name: Publish Jest unit test results
    uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
    if: always()
    with:
      github_token: ${{ github.token }}
      files: "${{ env.JEST_JUNIT_OUTPUT_DIR }}/*.xml"
      check_name: Jest Unit Test Results
      comment_mode: update last
      comment_title: Jest Unit Test Statistics
  
  - name: Publish Jest coverage report
    uses: actions/upload-artifact@v2
    if: always()
    with:
      name: jest-coverage-report
      path: ${{ env.JEST_COVERAGE_REPORT_DIR }}
      retention-days: 30
```

2022-04-21 20:31 UTC, ryandberger commented on doc/unit-testing-with-jest-and-rtl.md
> +The CI configuration knows to find the coverasge analysis results in `artifacts/coverage-jest`, which is where the Jest configuration says to leave them, so coverage artifacts will appear in Jenkins.
Is this a typo?

2022-04-21 20:46 UTC, ryandberger commented on doc/unit-testing-with-jest-and-rtl.md
> +The CI configuration knows to find the coverasge analysis results in `artifacts/coverage-jest`, which is where the Jest configuration says to leave them, so coverage artifacts will appear in Jenkins.
Found the type in the doc. Taken care of.

2022-04-21 20:54 UTC, zburke approved these changes
LGTM!

2022-04-22 00:59 UTC, mkuklis approved these changes

2022-04-22 13:37 UTC, merged